create extension if not exists "http" with schema "extensions";


create type "public"."division" as enum ('X', 'O', 'W', 'MU', 'MM', 'ML', 'WU', 'WL');

create type "public"."game_id" as enum ('PP', 'CP1', 'CP2', 'CP3', 'CP4', 'CP5', 'CP6', 'Q1', 'Q2', 'Q3', 'Q4', 'S1', 'S2', 'F', '3F', '5S1', '5S2', '5F', '7F', '9Q1', '9Q2', '9Q3', '9Q4', '9S1', '9S2', '9F', '11F', '13S1', '13S2', '13F', '15F', '9RR');

create type "public"."location_type" as enum ('Field', 'Entrance', 'Tourney Central', 'Lot 1 (Grass)', 'Lot 2 (Pavement)');

create type "public"."request_status" as enum ('pending', 'confirmed', 'resolved', 'expired');

create type "public"."request_type" as enum ('medical', 'water', 'transport');

create type "public"."vendor_type" as enum ('sponsor', 'vendor');

create sequence "public"."anonymous_tokens_id_seq";

create sequence "public"."datetime_id_seq_new";

create sequence "public"."deletion_tokens_id_seq";

create sequence "public"."divisions_id_seq";

create sequence "public"."favorite_teams_id_seq";

create sequence "public"."fields_id_seq";

create sequence "public"."games_id_seq";

create sequence "public"."notification_read_status_id_seq";

create sequence "public"."notifications_id_seq";

create sequence "public"."pools_id_seq";

create sequence "public"."rankings_id_seq";

create sequence "public"."rounds_id_seq";

create sequence "public"."schedule_options_id_seq";

create sequence "public"."scores_id_seq";

create sequence "public"."teams_new_id_seq1";

create sequence "public"."teams_pool_id_seq";

create sequence "public"."vendors_id_seq";

create table "public"."anonymous_tokens" (
    "id" integer not null default nextval('anonymous_tokens_id_seq'::regclass),
    "device_id" text not null,
    "token" text not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."anonymous_tokens" enable row level security;

create table "public"."cart_requests" (
    "id" bigint generated by default as identity not null,
    "from_location" location_type not null,
    "to_location" location_type not null,
    "from_field_number" integer,
    "to_field_number" integer,
    "status" request_status not null default 'pending'::request_status,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "requester_token" text,
    "passenger_count" smallint,
    "special_request" text default 'none'::text,
    "driver" uuid,
    "anon_device_id" text,
    "requester" text,
    "requester_id" uuid
);


alter table "public"."cart_requests" enable row level security;

create table "public"."datetime" (
    "id" integer not null default nextval('datetime_id_seq_new'::regclass),
    "time" time without time zone not null,
    "date" timestamp with time zone
);


alter table "public"."datetime" enable row level security;

create table "public"."deletion_tokens" (
    "id" integer not null default nextval('deletion_tokens_id_seq'::regclass),
    "user_id" uuid not null,
    "token" text not null,
    "created_at" timestamp with time zone default now(),
    "expires_at" timestamp with time zone not null
);


alter table "public"."deletion_tokens" enable row level security;

create table "public"."divisions" (
    "id" integer not null default nextval('divisions_id_seq'::regclass),
    "code" text not null,
    "title" text not null,
    "color" text not null,
    "icon" text,
    "display_order" integer,
    "color_light" text
);


alter table "public"."divisions" enable row level security;

create table "public"."faq" (
    "id" bigint generated by default as identity not null,
    "question" text not null,
    "answer" text
);


alter table "public"."faq" enable row level security;

create table "public"."favorite_teams" (
    "id" integer not null default nextval('favorite_teams_id_seq'::regclass),
    "user_id" uuid not null,
    "team_id" integer not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
);


alter table "public"."favorite_teams" enable row level security;

create table "public"."feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "subject" text,
    "message" text,
    "screenshots" text[],
    "display" boolean
);


alter table "public"."feedback" enable row level security;

create table "public"."fields" (
    "id" integer not null default nextval('fields_id_seq'::regclass),
    "name" text not null,
    "location" text
);


alter table "public"."fields" enable row level security;

create table "public"."games" (
    "id" integer not null default nextval('games_id_seq'::regclass),
    "pool_id" integer,
    "team1_id" integer,
    "team2_id" integer,
    "field_id" integer,
    "round_id" integer,
    "datetime_id" integer,
    "division_id" integer,
    "gametype_id" integer
);


alter table "public"."games" enable row level security;

create table "public"."gametypes" (
    "id" integer not null default nextval('schedule_options_id_seq'::regclass),
    "division_id" integer,
    "title" text not null,
    "route" text not null,
    "icon" text,
    "icon_color" text,
    "bg_color" text,
    "display_order" integer
);


alter table "public"."gametypes" enable row level security;

create table "public"."medical_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "field_number" integer,
    "status" request_status default 'pending'::request_status,
    "trainer" text,
    "priority_level" text,
    "assigned_to" uuid,
    "description_of_emergency" text,
    "team_name" text
);


alter table "public"."medical_requests" enable row level security;

create table "public"."notification_read_status" (
    "id" integer not null default nextval('notification_read_status_id_seq'::regclass),
    "notification_id" integer,
    "user_id" uuid,
    "read_at" timestamp with time zone default now(),
    "device_id" text
);


alter table "public"."notification_read_status" enable row level security;

create table "public"."notifications" (
    "id" integer not null default nextval('notifications_id_seq'::regclass),
    "user_id" uuid,
    "title" text not null,
    "message" text not null,
    "type" text not null default 'announcement'::text,
    "is_read" boolean default false,
    "created_at" timestamp with time zone default now()
);


alter table "public"."notifications" enable row level security;

create table "public"."pools" (
    "id" integer not null default nextval('pools_id_seq'::regclass),
    "name" text not null,
    "division_id" integer
);


alter table "public"."pools" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone,
    "full_name" text,
    "is_admin" boolean default false,
    "expo_push_token" text,
    "is_medical_staff" boolean default false,
    "is_logged_in" boolean default false,
    "is_volunteer" boolean default false,
    "is_available" boolean default false,
    "avatar_url" text,
    "is_driver" boolean default false,
    "role_id" smallint not null
);


alter table "public"."profiles" enable row level security;

create table "public"."rankings" (
    "team_id" integer not null,
    "wins" integer default 0,
    "losses" integer default 0,
    "pool_rank" integer,
    "id" integer generated by default as identity not null
);


alter table "public"."rankings" enable row level security;

create table "public"."restaurants" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "website" text,
    "discount" text,
    "category" text
);


alter table "public"."restaurants" enable row level security;

create table "public"."rounds" (
    "id" integer not null default nextval('rounds_id_seq'::regclass),
    "stage" text not null,
    "place" smallint
);


alter table "public"."rounds" enable row level security;

create table "public"."scores" (
    "id" integer not null default nextval('scores_id_seq'::regclass),
    "game_id" integer,
    "team1_score" integer not null,
    "team2_score" integer not null,
    "is_finished" boolean default false,
    "round_id" integer
);


alter table "public"."scores" enable row level security;

create table "public"."teams" (
    "name" text not null,
    "avatar_uri" text,
    "id" integer generated always as identity not null,
    "pool_id" integer default nextval('teams_pool_id_seq'::regclass),
    "seed" integer,
    "division_id" integer
);


alter table "public"."teams" enable row level security;

create table "public"."vendors" (
    "id" integer not null default nextval('vendors_id_seq'::regclass),
    "name" text,
    "avatar_url" text,
    "website" text,
    "type" vendor_type
);


alter table "public"."vendors" enable row level security;

create table "public"."volunteers" (
    "badge" text,
    "role" text,
    "id" smallint generated by default as identity not null,
    "avatar_uri" text,
    "email" text
);


alter table "public"."volunteers" enable row level security;

create table "public"."water_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "field_number" integer,
    "status" request_status default 'pending'::request_status,
    "volunteer" text,
    "updated_at" timestamp with time zone default now()
);


alter table "public"."water_requests" enable row level security;

alter sequence "public"."anonymous_tokens_id_seq" owned by "public"."anonymous_tokens"."id";

alter sequence "public"."deletion_tokens_id_seq" owned by "public"."deletion_tokens"."id";

alter sequence "public"."divisions_id_seq" owned by "public"."divisions"."id";

alter sequence "public"."favorite_teams_id_seq" owned by "public"."favorite_teams"."id";

alter sequence "public"."fields_id_seq" owned by "public"."fields"."id";

alter sequence "public"."games_id_seq" owned by "public"."games"."id";

alter sequence "public"."notification_read_status_id_seq" owned by "public"."notification_read_status"."id";

alter sequence "public"."notifications_id_seq" owned by "public"."notifications"."id";

alter sequence "public"."pools_id_seq" owned by "public"."pools"."id";

alter sequence "public"."rankings_id_seq" owned by "public"."rankings"."id";

alter sequence "public"."rounds_id_seq" owned by "public"."rounds"."id";

alter sequence "public"."schedule_options_id_seq" owned by "public"."gametypes"."id";

alter sequence "public"."scores_id_seq" owned by "public"."scores"."id";

alter sequence "public"."teams_new_id_seq1" owned by "public"."teams"."id";

alter sequence "public"."teams_pool_id_seq" owned by "public"."teams"."pool_id";

alter sequence "public"."vendors_id_seq" owned by "public"."vendors"."id";

CREATE UNIQUE INDEX anonymous_tokens_device_id_key ON public.anonymous_tokens USING btree (device_id);

CREATE UNIQUE INDEX anonymous_tokens_pkey ON public.anonymous_tokens USING btree (id);

CREATE UNIQUE INDEX cart_requests_pkey ON public.cart_requests USING btree (id);

CREATE UNIQUE INDEX datetime_id_key ON public.datetime USING btree (id);

CREATE UNIQUE INDEX datetime_pkey ON public.datetime USING btree (id);

CREATE UNIQUE INDEX deletion_tokens_pkey ON public.deletion_tokens USING btree (id);

CREATE UNIQUE INDEX deletion_tokens_token_key ON public.deletion_tokens USING btree (token);

CREATE UNIQUE INDEX divisions_code_key ON public.divisions USING btree (code);

CREATE UNIQUE INDEX divisions_pkey ON public.divisions USING btree (id);

CREATE UNIQUE INDEX faq_pkey ON public.faq USING btree (id);

CREATE UNIQUE INDEX favorite_teams_pkey ON public.favorite_teams USING btree (id);

CREATE UNIQUE INDEX favorite_teams_user_id_team_id_key ON public.favorite_teams USING btree (user_id, team_id);

CREATE UNIQUE INDEX feedback_pkey ON public.feedback USING btree (id);

CREATE UNIQUE INDEX fields_name_key ON public.fields USING btree (name);

CREATE UNIQUE INDEX fields_pkey ON public.fields USING btree (id);

CREATE UNIQUE INDEX games_pkey ON public.games USING btree (id);

CREATE INDEX idx_cart_requests_requester_id ON public.cart_requests USING btree (requester_id);

CREATE UNIQUE INDEX medical_requests_id_key ON public.medical_requests USING btree (id);

CREATE UNIQUE INDEX notification_read_status_pkey ON public.notification_read_status USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON public.medical_requests USING btree (id);

CREATE UNIQUE INDEX notifications_pkey1 ON public.notifications USING btree (id);

CREATE UNIQUE INDEX pool_standings_id_key ON public.rankings USING btree (id);

CREATE UNIQUE INDEX pool_standings_pkey ON public.rankings USING btree (id);

CREATE UNIQUE INDEX pools_pkey ON public.pools USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE INDEX profiles_role_id_idx ON public.profiles USING btree (role_id);

CREATE UNIQUE INDEX restaurants_pkey ON public.restaurants USING btree (id);

CREATE UNIQUE INDEX rounds_id_key ON public.rounds USING btree (id);

CREATE UNIQUE INDEX rounds_pkey ON public.rounds USING btree (id);

CREATE UNIQUE INDEX schedule_options_pkey ON public.gametypes USING btree (id);

CREATE UNIQUE INDEX scores_pkey ON public.scores USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX unique_team_id ON public.rankings USING btree (team_id);

CREATE UNIQUE INDEX unique_user_notification ON public.notification_read_status USING btree (user_id, notification_id);

CREATE UNIQUE INDEX vendors_pkey ON public.vendors USING btree (id);

CREATE UNIQUE INDEX volunteers_pkey ON public.volunteers USING btree (id);

CREATE UNIQUE INDEX water_refill_pkey ON public.water_requests USING btree (id);

alter table "public"."anonymous_tokens" add constraint "anonymous_tokens_pkey" PRIMARY KEY using index "anonymous_tokens_pkey";

alter table "public"."cart_requests" add constraint "cart_requests_pkey" PRIMARY KEY using index "cart_requests_pkey";

alter table "public"."datetime" add constraint "datetime_pkey" PRIMARY KEY using index "datetime_pkey";

alter table "public"."deletion_tokens" add constraint "deletion_tokens_pkey" PRIMARY KEY using index "deletion_tokens_pkey";

alter table "public"."divisions" add constraint "divisions_pkey" PRIMARY KEY using index "divisions_pkey";

alter table "public"."faq" add constraint "faq_pkey" PRIMARY KEY using index "faq_pkey";

alter table "public"."favorite_teams" add constraint "favorite_teams_pkey" PRIMARY KEY using index "favorite_teams_pkey";

alter table "public"."feedback" add constraint "feedback_pkey" PRIMARY KEY using index "feedback_pkey";

alter table "public"."fields" add constraint "fields_pkey" PRIMARY KEY using index "fields_pkey";

alter table "public"."games" add constraint "games_pkey" PRIMARY KEY using index "games_pkey";

alter table "public"."gametypes" add constraint "schedule_options_pkey" PRIMARY KEY using index "schedule_options_pkey";

alter table "public"."medical_requests" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."notification_read_status" add constraint "notification_read_status_pkey" PRIMARY KEY using index "notification_read_status_pkey";

alter table "public"."notifications" add constraint "notifications_pkey1" PRIMARY KEY using index "notifications_pkey1";

alter table "public"."pools" add constraint "pools_pkey" PRIMARY KEY using index "pools_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."rankings" add constraint "pool_standings_pkey" PRIMARY KEY using index "pool_standings_pkey";

alter table "public"."restaurants" add constraint "restaurants_pkey" PRIMARY KEY using index "restaurants_pkey";

alter table "public"."rounds" add constraint "rounds_pkey" PRIMARY KEY using index "rounds_pkey";

alter table "public"."scores" add constraint "scores_pkey" PRIMARY KEY using index "scores_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."vendors" add constraint "vendors_pkey" PRIMARY KEY using index "vendors_pkey";

alter table "public"."volunteers" add constraint "volunteers_pkey" PRIMARY KEY using index "volunteers_pkey";

alter table "public"."water_requests" add constraint "water_refill_pkey" PRIMARY KEY using index "water_refill_pkey";

alter table "public"."anonymous_tokens" add constraint "anonymous_tokens_device_id_key" UNIQUE using index "anonymous_tokens_device_id_key";

alter table "public"."cart_requests" add constraint "cart_requests_anon_device_id_fkey" FOREIGN KEY (anon_device_id) REFERENCES anonymous_tokens(device_id) not valid;

alter table "public"."cart_requests" validate constraint "cart_requests_anon_device_id_fkey";

alter table "public"."cart_requests" add constraint "cart_requests_driver_fkey" FOREIGN KEY (driver) REFERENCES profiles(id) not valid;

alter table "public"."cart_requests" validate constraint "cart_requests_driver_fkey";

alter table "public"."cart_requests" add constraint "cart_requests_from_field_number_fkey" FOREIGN KEY (from_field_number) REFERENCES fields(id) not valid;

alter table "public"."cart_requests" validate constraint "cart_requests_from_field_number_fkey";

alter table "public"."cart_requests" add constraint "cart_requests_requester_id_fkey" FOREIGN KEY (requester_id) REFERENCES profiles(id) not valid;

alter table "public"."cart_requests" validate constraint "cart_requests_requester_id_fkey";

alter table "public"."cart_requests" add constraint "cart_requests_to_field_number_fkey" FOREIGN KEY (to_field_number) REFERENCES fields(id) not valid;

alter table "public"."cart_requests" validate constraint "cart_requests_to_field_number_fkey";

alter table "public"."cart_requests" add constraint "check_from_field_number" CHECK ((((from_location = 'Field'::location_type) AND (from_field_number IS NOT NULL)) OR ((from_location <> 'Field'::location_type) AND (from_field_number IS NULL)))) not valid;

alter table "public"."cart_requests" validate constraint "check_from_field_number";

alter table "public"."cart_requests" add constraint "check_to_field_number" CHECK ((((to_location = 'Field'::location_type) AND (to_field_number IS NOT NULL)) OR ((to_location <> 'Field'::location_type) AND (to_field_number IS NULL)))) not valid;

alter table "public"."cart_requests" validate constraint "check_to_field_number";

alter table "public"."datetime" add constraint "datetime_id_key" UNIQUE using index "datetime_id_key";

alter table "public"."deletion_tokens" add constraint "deletion_tokens_token_key" UNIQUE using index "deletion_tokens_token_key";

alter table "public"."deletion_tokens" add constraint "fk_user" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."deletion_tokens" validate constraint "fk_user";

alter table "public"."divisions" add constraint "divisions_code_key" UNIQUE using index "divisions_code_key";

alter table "public"."favorite_teams" add constraint "favorite_teams_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."favorite_teams" validate constraint "favorite_teams_team_id_fkey";

alter table "public"."favorite_teams" add constraint "favorite_teams_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."favorite_teams" validate constraint "favorite_teams_user_id_fkey";

alter table "public"."favorite_teams" add constraint "favorite_teams_user_id_team_id_key" UNIQUE using index "favorite_teams_user_id_team_id_key";

alter table "public"."fields" add constraint "fields_name_key" UNIQUE using index "fields_name_key";

alter table "public"."games" add constraint "games_datetime_id_fkey" FOREIGN KEY (datetime_id) REFERENCES datetime(id) not valid;

alter table "public"."games" validate constraint "games_datetime_id_fkey";

alter table "public"."games" add constraint "games_division_id_fkey" FOREIGN KEY (division_id) REFERENCES divisions(id) not valid;

alter table "public"."games" validate constraint "games_division_id_fkey";

alter table "public"."games" add constraint "games_field_id_fkey" FOREIGN KEY (field_id) REFERENCES fields(id) not valid;

alter table "public"."games" validate constraint "games_field_id_fkey";

alter table "public"."games" add constraint "games_gametype_id_fkey" FOREIGN KEY (gametype_id) REFERENCES gametypes(id) not valid;

alter table "public"."games" validate constraint "games_gametype_id_fkey";

alter table "public"."games" add constraint "games_pool_id_fkey" FOREIGN KEY (pool_id) REFERENCES pools(id) not valid;

alter table "public"."games" validate constraint "games_pool_id_fkey";

alter table "public"."games" add constraint "games_round_id_fkey" FOREIGN KEY (round_id) REFERENCES rounds(id) not valid;

alter table "public"."games" validate constraint "games_round_id_fkey";

alter table "public"."games" add constraint "games_team1_id_fkey" FOREIGN KEY (team1_id) REFERENCES teams(id) not valid;

alter table "public"."games" validate constraint "games_team1_id_fkey";

alter table "public"."games" add constraint "games_team2_id_fkey" FOREIGN KEY (team2_id) REFERENCES teams(id) not valid;

alter table "public"."games" validate constraint "games_team2_id_fkey";

alter table "public"."gametypes" add constraint "gametypes_division_id_fkey" FOREIGN KEY (division_id) REFERENCES divisions(id) not valid;

alter table "public"."gametypes" validate constraint "gametypes_division_id_fkey";

alter table "public"."medical_requests" add constraint "medical_requests_assigned_to_fkey" FOREIGN KEY (assigned_to) REFERENCES profiles(id) not valid;

alter table "public"."medical_requests" validate constraint "medical_requests_assigned_to_fkey";

alter table "public"."medical_requests" add constraint "medical_requests_field_number_fkey" FOREIGN KEY (field_number) REFERENCES fields(id) not valid;

alter table "public"."medical_requests" validate constraint "medical_requests_field_number_fkey";

alter table "public"."medical_requests" add constraint "medical_requests_id_key" UNIQUE using index "medical_requests_id_key";

alter table "public"."notification_read_status" add constraint "notification_read_status_notification_id_fkey" FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE not valid;

alter table "public"."notification_read_status" validate constraint "notification_read_status_notification_id_fkey";

alter table "public"."notification_read_status" add constraint "notification_read_status_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."notification_read_status" validate constraint "notification_read_status_user_id_fkey";

alter table "public"."notification_read_status" add constraint "unique_user_notification" UNIQUE using index "unique_user_notification";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

alter table "public"."pools" add constraint "pools_division_id_fkey" FOREIGN KEY (division_id) REFERENCES divisions(id) not valid;

alter table "public"."pools" validate constraint "pools_division_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."profiles" validate constraint "profiles_role_id_fkey";

alter table "public"."rankings" add constraint "pool_standings_id_key" UNIQUE using index "pool_standings_id_key";

alter table "public"."rankings" add constraint "rankings_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) not valid;

alter table "public"."rankings" validate constraint "rankings_team_id_fkey";

alter table "public"."rankings" add constraint "unique_team_id" UNIQUE using index "unique_team_id";

alter table "public"."rounds" add constraint "rounds_id_key" UNIQUE using index "rounds_id_key";

alter table "public"."scores" add constraint "scores_game_id_fkey" FOREIGN KEY (game_id) REFERENCES games(id) not valid;

alter table "public"."scores" validate constraint "scores_game_id_fkey";

alter table "public"."teams" add constraint "fk_pool" FOREIGN KEY (pool_id) REFERENCES pools(id) ON DELETE SET NULL not valid;

alter table "public"."teams" validate constraint "fk_pool";

alter table "public"."teams" add constraint "teams_division_id_fkey" FOREIGN KEY (division_id) REFERENCES divisions(id) not valid;

alter table "public"."teams" validate constraint "teams_division_id_fkey";

alter table "public"."water_requests" add constraint "water_refill_field_number_fkey" FOREIGN KEY (field_number) REFERENCES fields(id) not valid;

alter table "public"."water_requests" validate constraint "water_refill_field_number_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.calculate_tiebreakers()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  curr_wins INT;
  num_teams INT;
  curr_rank INT;
  pool_id_var INT;
BEGIN
  -- Create a temporary table to store win counts
  CREATE TEMPORARY TABLE win_count AS
  SELECT t.pool_id, r.wins, COUNT(*) as cnt
  FROM rankings r
  JOIN teams t ON r.team_id = t.id
  GROUP BY t.pool_id, r.wins;

  -- Process each pool
  FOR pool_id_var IN SELECT DISTINCT pool_id FROM teams LOOP
    curr_rank := 1;

    -- Process teams in descending order of wins
    FOR curr_wins, num_teams IN 
      SELECT wins, cnt 
      FROM win_count 
      WHERE pool_id = pool_id_var
      ORDER BY wins DESC
    LOOP
      -- Always use tiebreakers, even for single teams
      WITH tied_teams AS (
        SELECT r.team_id, r.wins, r.losses
        FROM rankings r
        JOIN teams t ON r.team_id = t.id
        WHERE t.pool_id = pool_id_var AND r.wins = curr_wins
      ),
      game_results AS (
        SELECT 
          g.team1_id,
          g.team2_id,
          s.team1_score,
          s.team2_score,
          g.id AS game_id,
          CASE
            WHEN s.team1_score > s.team2_score THEN g.team1_id
            ELSE g.team2_id
          END AS winner_id
        FROM games g
        JOIN scores s ON s.game_id = g.id
        WHERE g.pool_id = pool_id_var
          AND s.is_finished = true
          AND (g.team1_id IN (SELECT team_id FROM tied_teams) OR g.team2_id IN (SELECT team_id FROM tied_teams))
      ),
      point_diff AS (
        SELECT
          t.team_id,
          SUM(
            CASE
              WHEN gr.team1_id = t.team_id THEN gr.team1_score - gr.team2_score
              ELSE gr.team2_score - gr.team1_score
            END
          ) AS point_differential
        FROM tied_teams t
        JOIN game_results gr ON t.team_id = gr.team1_id OR t.team_id = gr.team2_id
        GROUP BY t.team_id
      ),
      ranked_teams AS (
        SELECT
          t.team_id,
          t.wins,
          t.losses,
          COALESCE(pd.point_differential, 0) AS point_differential,
          ROW_NUMBER() OVER (
            ORDER BY
              t.wins DESC,
              COALESCE(pd.point_differential, 0) DESC
          ) AS calculated_rank
        FROM tied_teams t
        LEFT JOIN point_diff pd ON t.team_id = pd.team_id
      )
      UPDATE rankings r
      SET pool_rank = curr_rank + rt.calculated_rank - 1
      FROM ranked_teams rt
      WHERE r.team_id = rt.team_id;

      curr_rank := curr_rank + num_teams;
    END LOOP;
  END LOOP;

  -- Clean up
  DROP TABLE win_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_favorites_limit()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    -- Explicitly set an empty search path
    SET search_path = '';
    
    -- Use fully qualified table name
    IF (
        SELECT COUNT(*)
        FROM public.favorite_teams
        WHERE user_id = NEW.user_id
    ) >= 5 THEN
        RAISE EXCEPTION 'Users can only favorite up to 5 teams.';
    END IF;
    
    RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.client_update_rankings_and_tiebreakers()
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
  -- Call the helper function
  PERFORM update_pool_rankings();
  PERFORM calculate_tiebreakers();
END;$function$
;

CREATE OR REPLACE FUNCTION public.create_deletion_tokens_table_if_not_exists()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  CREATE TABLE IF NOT EXISTS public.deletion_tokens (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    token TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
  );
END;
$function$
;

create or replace view "public"."full_gameview" as  SELECT g.id,
    g.pool_id,
    g.division_id,
    divisions.title AS division,
    t1.name AS team1_name,
    t2.name AS team2_name,
    s.team1_score,
    s.team2_score,
    fields.name AS field,
    gametypes.title AS gametype,
    rounds.stage,
    datetime.date,
    datetime."time"
   FROM ((((((((games g
     LEFT JOIN divisions ON ((divisions.id = g.division_id)))
     LEFT JOIN datetime ON ((datetime.id = g.datetime_id)))
     LEFT JOIN scores s ON ((s.game_id = g.id)))
     LEFT JOIN teams t1 ON ((t1.id = g.team1_id)))
     LEFT JOIN teams t2 ON ((t2.id = g.team2_id)))
     LEFT JOIN fields ON ((fields.id = g.field_id)))
     LEFT JOIN gametypes ON ((gametypes.id = g.gametype_id)))
     LEFT JOIN rounds ON ((rounds.id = g.round_id)))
  ORDER BY g.division_id, g.round_id;


create or replace view "public"."full_ranking" as  SELECT t.name,
    t.pool_id,
    rankings.team_id,
    rankings.wins,
    rankings.losses,
    rankings.pool_rank,
    rankings.id
   FROM (rankings
     JOIN teams t ON ((t.id = rankings.team_id)))
  ORDER BY t.pool_id;


create or replace view "public"."full_scores" as  SELECT t1.name AS team1_name,
    t2.name AS team2_name,
    g.pool_id,
    s.team1_score,
    s.team2_score,
    s.is_finished,
    s.id
   FROM (((games g
     JOIN scores s ON ((s.game_id = g.id)))
     JOIN teams t1 ON ((t1.id = g.team1_id)))
     JOIN teams t2 ON ((t2.id = g.team2_id)))
  ORDER BY g.pool_id;


CREATE OR REPLACE FUNCTION public.handle_anonymous_token(p_device_id text, p_token text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
  existing_record_count INTEGER;
BEGIN
  -- Check if a record exists with this device_id
  SELECT COUNT(*) INTO existing_record_count 
  FROM public.anonymous_tokens
  WHERE device_id = p_device_id;
  
  -- If record exists, update it
  IF existing_record_count > 0 THEN
    UPDATE public.anonymous_tokens
    SET token = p_token,
        updated_at = NOW()
    WHERE device_id = p_device_id;
  -- Otherwise, insert a new record
  ELSE
    INSERT INTO public.anonymous_tokens (device_id, token, created_at, updated_at)
    VALUES (p_device_id, p_token, NOW(), NOW());
  END IF;
  
  -- Return success
  RETURN;
EXCEPTION
  WHEN unique_violation THEN
    -- If we somehow hit a constraint violation anyway,
    -- try again with a different approach
    DELETE FROM public.anonymous_tokens WHERE device_id = p_device_id;
    
    -- Small artificial delay to ensure deletion is processed
    PERFORM pg_sleep(0.5);
    
    -- Try insert again
    INSERT INTO public.anonymous_tokens (device_id, token, created_at, updated_at)
    VALUES (p_device_id, p_token, NOW(), NOW());
    
    RETURN;
  WHEN OTHERS THEN
    -- Log other exceptions but don't raise to client
    RAISE WARNING 'Error in handle_anonymous_token: %', SQLERRM;
    RETURN;
END;$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_new_rankings()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  game_record RECORD;
BEGIN
  -- Fetch the corresponding game record
  SELECT * INTO game_record FROM games WHERE id = NEW.game_id;
  
  -- Check if the new game is a pool play game (assuming round_id 1 is for pool play)
  IF NEW.round_id = 1 THEN
    -- Insert or update ranking for team1 if it's not null
    IF game_record.team1_id IS NOT NULL THEN
      INSERT INTO rankings (team_id, wins, losses, pool_rank)
      VALUES (game_record.team1_id, 0, 0, 0)
      ON CONFLICT (team_id) 
      DO UPDATE SET wins = rankings.wins, losses = rankings.losses, pool_rank = rankings.pool_rank;
    END IF;
    
    -- Insert or update ranking for team2 if it's not null
    IF game_record.team2_id IS NOT NULL THEN
      INSERT INTO rankings (team_id, wins, losses, pool_rank)
      VALUES (game_record.team2_id, 0, 0, 0)
      ON CONFLICT (team_id) 
      DO UPDATE SET wins = rankings.wins, losses = rankings.losses, pool_rank = rankings.pool_rank;
    END IF;
  END IF;
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_new_score()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  INSERT INTO scores (game_id, team1_score, team2_score, is_finished, round_id)
  VALUES (NEW.id, 0, 0, false, NEW.round_id);
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.perform_rankings_and_tiebreakers()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
  -- Call the update_pool_rankings function
  PERFORM update_pool_rankings();
  
  -- Call the calculate_tiebreakers function
  PERFORM calculate_tiebreakers();
  
  RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.reset_bracket_scores(round_id_param integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE scores
  SET team1_score = 0, team2_score = 0, is_finished = false
  WHERE game_id IN (SELECT id FROM games WHERE round_id = round_id_param);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.reset_pool_scores(pool_id_param integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Reset scores
  UPDATE scores
  SET team1_score = 0, team2_score = 0, is_finished = false
  WHERE game_id IN (SELECT id FROM games WHERE pool_id = pool_id_param);

  -- Reset rankings
  UPDATE rankings
  SET wins = 0, losses = 0, pool_rank = NULL
  WHERE team_id IN (SELECT id FROM teams WHERE pool_id = pool_id_param);

  -- Optionally, you can also reset other ranking-related fields if they exist
  -- For example, if you have fields like points_for, points_against, etc.
  -- UPDATE rankings
  -- SET points_for = 0, points_against = 0
  -- WHERE team_id IN (SELECT id FROM teams WHERE pool_id = pool_id_param);

END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_pool_rankings()
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
  -- Update wins and losses in the rankings table, considering only PP games for all divisions
  UPDATE rankings r
  SET 
    wins = (
      SELECT COUNT(*) 
      FROM games g
      JOIN scores s ON g.id = s.game_id
      JOIN teams t ON r.team_id = t.id
      JOIN pools p on g.pool_id = p.id
      
      WHERE ((g.team1_id = r.team_id AND s.team1_score > s.team2_score)
         OR (g.team2_id = r.team_id AND s.team2_score > s.team1_score))
         AND s.is_finished = true
         AND g.round_id = 1  -- Assuming round_id 1 represents Pool Play
         AND g.division_id = p.division_id  -- Ensure games are from the same division as the team
    ),
    losses = (
      SELECT COUNT(*) 
      FROM games g
      JOIN scores s ON g.id = s.game_id
      JOIN teams t ON r.team_id = t.id
      JOIN pools p on g.pool_id = p.id
      
      WHERE ((g.team1_id = r.team_id AND s.team1_score < s.team2_score)
         OR (g.team2_id = r.team_id AND s.team2_score < s.team1_score))
         AND s.is_finished = true
         AND g.round_id = 1  -- Assuming round_id 1 represents Pool Play
         AND g.division_id = p.division_id  -- Ensure games are from the same division as the team
    )
  WHERE EXISTS (
    SELECT 1 FROM teams t WHERE t.id = r.team_id
  );

  -- Update pool_rank based on wins (initial ranking) for each division and pool
  UPDATE rankings r
  SET pool_rank = subquery.rank
  FROM (
    SELECT 
      r.id,
      RANK() OVER (PARTITION BY t.pool_id ORDER BY r.wins DESC, r.losses ASC) as rank
    FROM rankings r
    JOIN teams t ON r.team_id = t.id
  ) AS subquery
  WHERE r.id = subquery.id;

END;$function$
;

grant delete on table "public"."anonymous_tokens" to "anon";

grant insert on table "public"."anonymous_tokens" to "anon";

grant references on table "public"."anonymous_tokens" to "anon";

grant select on table "public"."anonymous_tokens" to "anon";

grant trigger on table "public"."anonymous_tokens" to "anon";

grant truncate on table "public"."anonymous_tokens" to "anon";

grant update on table "public"."anonymous_tokens" to "anon";

grant delete on table "public"."anonymous_tokens" to "authenticated";

grant insert on table "public"."anonymous_tokens" to "authenticated";

grant references on table "public"."anonymous_tokens" to "authenticated";

grant select on table "public"."anonymous_tokens" to "authenticated";

grant trigger on table "public"."anonymous_tokens" to "authenticated";

grant truncate on table "public"."anonymous_tokens" to "authenticated";

grant update on table "public"."anonymous_tokens" to "authenticated";

grant delete on table "public"."anonymous_tokens" to "service_role";

grant insert on table "public"."anonymous_tokens" to "service_role";

grant references on table "public"."anonymous_tokens" to "service_role";

grant select on table "public"."anonymous_tokens" to "service_role";

grant trigger on table "public"."anonymous_tokens" to "service_role";

grant truncate on table "public"."anonymous_tokens" to "service_role";

grant update on table "public"."anonymous_tokens" to "service_role";

grant delete on table "public"."cart_requests" to "anon";

grant insert on table "public"."cart_requests" to "anon";

grant references on table "public"."cart_requests" to "anon";

grant select on table "public"."cart_requests" to "anon";

grant trigger on table "public"."cart_requests" to "anon";

grant truncate on table "public"."cart_requests" to "anon";

grant update on table "public"."cart_requests" to "anon";

grant delete on table "public"."cart_requests" to "authenticated";

grant insert on table "public"."cart_requests" to "authenticated";

grant references on table "public"."cart_requests" to "authenticated";

grant select on table "public"."cart_requests" to "authenticated";

grant trigger on table "public"."cart_requests" to "authenticated";

grant truncate on table "public"."cart_requests" to "authenticated";

grant update on table "public"."cart_requests" to "authenticated";

grant delete on table "public"."cart_requests" to "service_role";

grant insert on table "public"."cart_requests" to "service_role";

grant references on table "public"."cart_requests" to "service_role";

grant select on table "public"."cart_requests" to "service_role";

grant trigger on table "public"."cart_requests" to "service_role";

grant truncate on table "public"."cart_requests" to "service_role";

grant update on table "public"."cart_requests" to "service_role";

grant delete on table "public"."datetime" to "anon";

grant insert on table "public"."datetime" to "anon";

grant references on table "public"."datetime" to "anon";

grant select on table "public"."datetime" to "anon";

grant trigger on table "public"."datetime" to "anon";

grant truncate on table "public"."datetime" to "anon";

grant update on table "public"."datetime" to "anon";

grant delete on table "public"."datetime" to "authenticated";

grant insert on table "public"."datetime" to "authenticated";

grant references on table "public"."datetime" to "authenticated";

grant select on table "public"."datetime" to "authenticated";

grant trigger on table "public"."datetime" to "authenticated";

grant truncate on table "public"."datetime" to "authenticated";

grant update on table "public"."datetime" to "authenticated";

grant delete on table "public"."datetime" to "service_role";

grant insert on table "public"."datetime" to "service_role";

grant references on table "public"."datetime" to "service_role";

grant select on table "public"."datetime" to "service_role";

grant trigger on table "public"."datetime" to "service_role";

grant truncate on table "public"."datetime" to "service_role";

grant update on table "public"."datetime" to "service_role";

grant delete on table "public"."deletion_tokens" to "anon";

grant insert on table "public"."deletion_tokens" to "anon";

grant references on table "public"."deletion_tokens" to "anon";

grant select on table "public"."deletion_tokens" to "anon";

grant trigger on table "public"."deletion_tokens" to "anon";

grant truncate on table "public"."deletion_tokens" to "anon";

grant update on table "public"."deletion_tokens" to "anon";

grant delete on table "public"."deletion_tokens" to "authenticated";

grant insert on table "public"."deletion_tokens" to "authenticated";

grant references on table "public"."deletion_tokens" to "authenticated";

grant select on table "public"."deletion_tokens" to "authenticated";

grant trigger on table "public"."deletion_tokens" to "authenticated";

grant truncate on table "public"."deletion_tokens" to "authenticated";

grant update on table "public"."deletion_tokens" to "authenticated";

grant delete on table "public"."deletion_tokens" to "service_role";

grant insert on table "public"."deletion_tokens" to "service_role";

grant references on table "public"."deletion_tokens" to "service_role";

grant select on table "public"."deletion_tokens" to "service_role";

grant trigger on table "public"."deletion_tokens" to "service_role";

grant truncate on table "public"."deletion_tokens" to "service_role";

grant update on table "public"."deletion_tokens" to "service_role";

grant delete on table "public"."divisions" to "anon";

grant insert on table "public"."divisions" to "anon";

grant references on table "public"."divisions" to "anon";

grant select on table "public"."divisions" to "anon";

grant trigger on table "public"."divisions" to "anon";

grant truncate on table "public"."divisions" to "anon";

grant update on table "public"."divisions" to "anon";

grant delete on table "public"."divisions" to "authenticated";

grant insert on table "public"."divisions" to "authenticated";

grant references on table "public"."divisions" to "authenticated";

grant select on table "public"."divisions" to "authenticated";

grant trigger on table "public"."divisions" to "authenticated";

grant truncate on table "public"."divisions" to "authenticated";

grant update on table "public"."divisions" to "authenticated";

grant delete on table "public"."divisions" to "service_role";

grant insert on table "public"."divisions" to "service_role";

grant references on table "public"."divisions" to "service_role";

grant select on table "public"."divisions" to "service_role";

grant trigger on table "public"."divisions" to "service_role";

grant truncate on table "public"."divisions" to "service_role";

grant update on table "public"."divisions" to "service_role";

grant delete on table "public"."faq" to "anon";

grant insert on table "public"."faq" to "anon";

grant references on table "public"."faq" to "anon";

grant select on table "public"."faq" to "anon";

grant trigger on table "public"."faq" to "anon";

grant truncate on table "public"."faq" to "anon";

grant update on table "public"."faq" to "anon";

grant delete on table "public"."faq" to "authenticated";

grant insert on table "public"."faq" to "authenticated";

grant references on table "public"."faq" to "authenticated";

grant select on table "public"."faq" to "authenticated";

grant trigger on table "public"."faq" to "authenticated";

grant truncate on table "public"."faq" to "authenticated";

grant update on table "public"."faq" to "authenticated";

grant delete on table "public"."faq" to "service_role";

grant insert on table "public"."faq" to "service_role";

grant references on table "public"."faq" to "service_role";

grant select on table "public"."faq" to "service_role";

grant trigger on table "public"."faq" to "service_role";

grant truncate on table "public"."faq" to "service_role";

grant update on table "public"."faq" to "service_role";

grant delete on table "public"."favorite_teams" to "anon";

grant insert on table "public"."favorite_teams" to "anon";

grant references on table "public"."favorite_teams" to "anon";

grant select on table "public"."favorite_teams" to "anon";

grant trigger on table "public"."favorite_teams" to "anon";

grant truncate on table "public"."favorite_teams" to "anon";

grant update on table "public"."favorite_teams" to "anon";

grant delete on table "public"."favorite_teams" to "authenticated";

grant insert on table "public"."favorite_teams" to "authenticated";

grant references on table "public"."favorite_teams" to "authenticated";

grant select on table "public"."favorite_teams" to "authenticated";

grant trigger on table "public"."favorite_teams" to "authenticated";

grant truncate on table "public"."favorite_teams" to "authenticated";

grant update on table "public"."favorite_teams" to "authenticated";

grant delete on table "public"."favorite_teams" to "service_role";

grant insert on table "public"."favorite_teams" to "service_role";

grant references on table "public"."favorite_teams" to "service_role";

grant select on table "public"."favorite_teams" to "service_role";

grant trigger on table "public"."favorite_teams" to "service_role";

grant truncate on table "public"."favorite_teams" to "service_role";

grant update on table "public"."favorite_teams" to "service_role";

grant delete on table "public"."feedback" to "anon";

grant insert on table "public"."feedback" to "anon";

grant references on table "public"."feedback" to "anon";

grant select on table "public"."feedback" to "anon";

grant trigger on table "public"."feedback" to "anon";

grant truncate on table "public"."feedback" to "anon";

grant update on table "public"."feedback" to "anon";

grant delete on table "public"."feedback" to "authenticated";

grant insert on table "public"."feedback" to "authenticated";

grant references on table "public"."feedback" to "authenticated";

grant select on table "public"."feedback" to "authenticated";

grant trigger on table "public"."feedback" to "authenticated";

grant truncate on table "public"."feedback" to "authenticated";

grant update on table "public"."feedback" to "authenticated";

grant delete on table "public"."feedback" to "service_role";

grant insert on table "public"."feedback" to "service_role";

grant references on table "public"."feedback" to "service_role";

grant select on table "public"."feedback" to "service_role";

grant trigger on table "public"."feedback" to "service_role";

grant truncate on table "public"."feedback" to "service_role";

grant update on table "public"."feedback" to "service_role";

grant delete on table "public"."fields" to "anon";

grant insert on table "public"."fields" to "anon";

grant references on table "public"."fields" to "anon";

grant select on table "public"."fields" to "anon";

grant trigger on table "public"."fields" to "anon";

grant truncate on table "public"."fields" to "anon";

grant update on table "public"."fields" to "anon";

grant delete on table "public"."fields" to "authenticated";

grant insert on table "public"."fields" to "authenticated";

grant references on table "public"."fields" to "authenticated";

grant select on table "public"."fields" to "authenticated";

grant trigger on table "public"."fields" to "authenticated";

grant truncate on table "public"."fields" to "authenticated";

grant update on table "public"."fields" to "authenticated";

grant delete on table "public"."fields" to "service_role";

grant insert on table "public"."fields" to "service_role";

grant references on table "public"."fields" to "service_role";

grant select on table "public"."fields" to "service_role";

grant trigger on table "public"."fields" to "service_role";

grant truncate on table "public"."fields" to "service_role";

grant update on table "public"."fields" to "service_role";

grant delete on table "public"."games" to "anon";

grant insert on table "public"."games" to "anon";

grant references on table "public"."games" to "anon";

grant select on table "public"."games" to "anon";

grant trigger on table "public"."games" to "anon";

grant truncate on table "public"."games" to "anon";

grant update on table "public"."games" to "anon";

grant delete on table "public"."games" to "authenticated";

grant insert on table "public"."games" to "authenticated";

grant references on table "public"."games" to "authenticated";

grant select on table "public"."games" to "authenticated";

grant trigger on table "public"."games" to "authenticated";

grant truncate on table "public"."games" to "authenticated";

grant update on table "public"."games" to "authenticated";

grant delete on table "public"."games" to "service_role";

grant insert on table "public"."games" to "service_role";

grant references on table "public"."games" to "service_role";

grant select on table "public"."games" to "service_role";

grant trigger on table "public"."games" to "service_role";

grant truncate on table "public"."games" to "service_role";

grant update on table "public"."games" to "service_role";

grant delete on table "public"."gametypes" to "anon";

grant insert on table "public"."gametypes" to "anon";

grant references on table "public"."gametypes" to "anon";

grant select on table "public"."gametypes" to "anon";

grant trigger on table "public"."gametypes" to "anon";

grant truncate on table "public"."gametypes" to "anon";

grant update on table "public"."gametypes" to "anon";

grant delete on table "public"."gametypes" to "authenticated";

grant insert on table "public"."gametypes" to "authenticated";

grant references on table "public"."gametypes" to "authenticated";

grant select on table "public"."gametypes" to "authenticated";

grant trigger on table "public"."gametypes" to "authenticated";

grant truncate on table "public"."gametypes" to "authenticated";

grant update on table "public"."gametypes" to "authenticated";

grant delete on table "public"."gametypes" to "service_role";

grant insert on table "public"."gametypes" to "service_role";

grant references on table "public"."gametypes" to "service_role";

grant select on table "public"."gametypes" to "service_role";

grant trigger on table "public"."gametypes" to "service_role";

grant truncate on table "public"."gametypes" to "service_role";

grant update on table "public"."gametypes" to "service_role";

grant delete on table "public"."medical_requests" to "anon";

grant insert on table "public"."medical_requests" to "anon";

grant references on table "public"."medical_requests" to "anon";

grant select on table "public"."medical_requests" to "anon";

grant trigger on table "public"."medical_requests" to "anon";

grant truncate on table "public"."medical_requests" to "anon";

grant update on table "public"."medical_requests" to "anon";

grant delete on table "public"."medical_requests" to "authenticated";

grant insert on table "public"."medical_requests" to "authenticated";

grant references on table "public"."medical_requests" to "authenticated";

grant select on table "public"."medical_requests" to "authenticated";

grant trigger on table "public"."medical_requests" to "authenticated";

grant truncate on table "public"."medical_requests" to "authenticated";

grant update on table "public"."medical_requests" to "authenticated";

grant delete on table "public"."medical_requests" to "service_role";

grant insert on table "public"."medical_requests" to "service_role";

grant references on table "public"."medical_requests" to "service_role";

grant select on table "public"."medical_requests" to "service_role";

grant trigger on table "public"."medical_requests" to "service_role";

grant truncate on table "public"."medical_requests" to "service_role";

grant update on table "public"."medical_requests" to "service_role";

grant delete on table "public"."notification_read_status" to "anon";

grant insert on table "public"."notification_read_status" to "anon";

grant references on table "public"."notification_read_status" to "anon";

grant select on table "public"."notification_read_status" to "anon";

grant trigger on table "public"."notification_read_status" to "anon";

grant truncate on table "public"."notification_read_status" to "anon";

grant update on table "public"."notification_read_status" to "anon";

grant delete on table "public"."notification_read_status" to "authenticated";

grant insert on table "public"."notification_read_status" to "authenticated";

grant references on table "public"."notification_read_status" to "authenticated";

grant select on table "public"."notification_read_status" to "authenticated";

grant trigger on table "public"."notification_read_status" to "authenticated";

grant truncate on table "public"."notification_read_status" to "authenticated";

grant update on table "public"."notification_read_status" to "authenticated";

grant delete on table "public"."notification_read_status" to "service_role";

grant insert on table "public"."notification_read_status" to "service_role";

grant references on table "public"."notification_read_status" to "service_role";

grant select on table "public"."notification_read_status" to "service_role";

grant trigger on table "public"."notification_read_status" to "service_role";

grant truncate on table "public"."notification_read_status" to "service_role";

grant update on table "public"."notification_read_status" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."pools" to "anon";

grant insert on table "public"."pools" to "anon";

grant references on table "public"."pools" to "anon";

grant select on table "public"."pools" to "anon";

grant trigger on table "public"."pools" to "anon";

grant truncate on table "public"."pools" to "anon";

grant update on table "public"."pools" to "anon";

grant delete on table "public"."pools" to "authenticated";

grant insert on table "public"."pools" to "authenticated";

grant references on table "public"."pools" to "authenticated";

grant select on table "public"."pools" to "authenticated";

grant trigger on table "public"."pools" to "authenticated";

grant truncate on table "public"."pools" to "authenticated";

grant update on table "public"."pools" to "authenticated";

grant delete on table "public"."pools" to "service_role";

grant insert on table "public"."pools" to "service_role";

grant references on table "public"."pools" to "service_role";

grant select on table "public"."pools" to "service_role";

grant trigger on table "public"."pools" to "service_role";

grant truncate on table "public"."pools" to "service_role";

grant update on table "public"."pools" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."rankings" to "anon";

grant insert on table "public"."rankings" to "anon";

grant references on table "public"."rankings" to "anon";

grant select on table "public"."rankings" to "anon";

grant trigger on table "public"."rankings" to "anon";

grant truncate on table "public"."rankings" to "anon";

grant update on table "public"."rankings" to "anon";

grant delete on table "public"."rankings" to "authenticated";

grant insert on table "public"."rankings" to "authenticated";

grant references on table "public"."rankings" to "authenticated";

grant select on table "public"."rankings" to "authenticated";

grant trigger on table "public"."rankings" to "authenticated";

grant truncate on table "public"."rankings" to "authenticated";

grant update on table "public"."rankings" to "authenticated";

grant delete on table "public"."rankings" to "service_role";

grant insert on table "public"."rankings" to "service_role";

grant references on table "public"."rankings" to "service_role";

grant select on table "public"."rankings" to "service_role";

grant trigger on table "public"."rankings" to "service_role";

grant truncate on table "public"."rankings" to "service_role";

grant update on table "public"."rankings" to "service_role";

grant delete on table "public"."restaurants" to "anon";

grant insert on table "public"."restaurants" to "anon";

grant references on table "public"."restaurants" to "anon";

grant select on table "public"."restaurants" to "anon";

grant trigger on table "public"."restaurants" to "anon";

grant truncate on table "public"."restaurants" to "anon";

grant update on table "public"."restaurants" to "anon";

grant delete on table "public"."restaurants" to "authenticated";

grant insert on table "public"."restaurants" to "authenticated";

grant references on table "public"."restaurants" to "authenticated";

grant select on table "public"."restaurants" to "authenticated";

grant trigger on table "public"."restaurants" to "authenticated";

grant truncate on table "public"."restaurants" to "authenticated";

grant update on table "public"."restaurants" to "authenticated";

grant delete on table "public"."restaurants" to "service_role";

grant insert on table "public"."restaurants" to "service_role";

grant references on table "public"."restaurants" to "service_role";

grant select on table "public"."restaurants" to "service_role";

grant trigger on table "public"."restaurants" to "service_role";

grant truncate on table "public"."restaurants" to "service_role";

grant update on table "public"."restaurants" to "service_role";

grant delete on table "public"."rounds" to "anon";

grant insert on table "public"."rounds" to "anon";

grant references on table "public"."rounds" to "anon";

grant select on table "public"."rounds" to "anon";

grant trigger on table "public"."rounds" to "anon";

grant truncate on table "public"."rounds" to "anon";

grant update on table "public"."rounds" to "anon";

grant delete on table "public"."rounds" to "authenticated";

grant insert on table "public"."rounds" to "authenticated";

grant references on table "public"."rounds" to "authenticated";

grant select on table "public"."rounds" to "authenticated";

grant trigger on table "public"."rounds" to "authenticated";

grant truncate on table "public"."rounds" to "authenticated";

grant update on table "public"."rounds" to "authenticated";

grant delete on table "public"."rounds" to "service_role";

grant insert on table "public"."rounds" to "service_role";

grant references on table "public"."rounds" to "service_role";

grant select on table "public"."rounds" to "service_role";

grant trigger on table "public"."rounds" to "service_role";

grant truncate on table "public"."rounds" to "service_role";

grant update on table "public"."rounds" to "service_role";

grant delete on table "public"."scores" to "anon";

grant insert on table "public"."scores" to "anon";

grant references on table "public"."scores" to "anon";

grant select on table "public"."scores" to "anon";

grant trigger on table "public"."scores" to "anon";

grant truncate on table "public"."scores" to "anon";

grant update on table "public"."scores" to "anon";

grant delete on table "public"."scores" to "authenticated";

grant insert on table "public"."scores" to "authenticated";

grant references on table "public"."scores" to "authenticated";

grant select on table "public"."scores" to "authenticated";

grant trigger on table "public"."scores" to "authenticated";

grant truncate on table "public"."scores" to "authenticated";

grant update on table "public"."scores" to "authenticated";

grant delete on table "public"."scores" to "service_role";

grant insert on table "public"."scores" to "service_role";

grant references on table "public"."scores" to "service_role";

grant select on table "public"."scores" to "service_role";

grant trigger on table "public"."scores" to "service_role";

grant truncate on table "public"."scores" to "service_role";

grant update on table "public"."scores" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."vendors" to "anon";

grant insert on table "public"."vendors" to "anon";

grant references on table "public"."vendors" to "anon";

grant select on table "public"."vendors" to "anon";

grant trigger on table "public"."vendors" to "anon";

grant truncate on table "public"."vendors" to "anon";

grant update on table "public"."vendors" to "anon";

grant delete on table "public"."vendors" to "authenticated";

grant insert on table "public"."vendors" to "authenticated";

grant references on table "public"."vendors" to "authenticated";

grant select on table "public"."vendors" to "authenticated";

grant trigger on table "public"."vendors" to "authenticated";

grant truncate on table "public"."vendors" to "authenticated";

grant update on table "public"."vendors" to "authenticated";

grant delete on table "public"."vendors" to "service_role";

grant insert on table "public"."vendors" to "service_role";

grant references on table "public"."vendors" to "service_role";

grant select on table "public"."vendors" to "service_role";

grant trigger on table "public"."vendors" to "service_role";

grant truncate on table "public"."vendors" to "service_role";

grant update on table "public"."vendors" to "service_role";

grant delete on table "public"."volunteers" to "anon";

grant insert on table "public"."volunteers" to "anon";

grant references on table "public"."volunteers" to "anon";

grant select on table "public"."volunteers" to "anon";

grant trigger on table "public"."volunteers" to "anon";

grant truncate on table "public"."volunteers" to "anon";

grant update on table "public"."volunteers" to "anon";

grant delete on table "public"."volunteers" to "authenticated";

grant insert on table "public"."volunteers" to "authenticated";

grant references on table "public"."volunteers" to "authenticated";

grant select on table "public"."volunteers" to "authenticated";

grant trigger on table "public"."volunteers" to "authenticated";

grant truncate on table "public"."volunteers" to "authenticated";

grant update on table "public"."volunteers" to "authenticated";

grant delete on table "public"."volunteers" to "service_role";

grant insert on table "public"."volunteers" to "service_role";

grant references on table "public"."volunteers" to "service_role";

grant select on table "public"."volunteers" to "service_role";

grant trigger on table "public"."volunteers" to "service_role";

grant truncate on table "public"."volunteers" to "service_role";

grant update on table "public"."volunteers" to "service_role";

grant delete on table "public"."water_requests" to "anon";

grant insert on table "public"."water_requests" to "anon";

grant references on table "public"."water_requests" to "anon";

grant select on table "public"."water_requests" to "anon";

grant trigger on table "public"."water_requests" to "anon";

grant truncate on table "public"."water_requests" to "anon";

grant update on table "public"."water_requests" to "anon";

grant delete on table "public"."water_requests" to "authenticated";

grant insert on table "public"."water_requests" to "authenticated";

grant references on table "public"."water_requests" to "authenticated";

grant select on table "public"."water_requests" to "authenticated";

grant trigger on table "public"."water_requests" to "authenticated";

grant truncate on table "public"."water_requests" to "authenticated";

grant update on table "public"."water_requests" to "authenticated";

grant delete on table "public"."water_requests" to "service_role";

grant insert on table "public"."water_requests" to "service_role";

grant references on table "public"."water_requests" to "service_role";

grant select on table "public"."water_requests" to "service_role";

grant trigger on table "public"."water_requests" to "service_role";

grant truncate on table "public"."water_requests" to "service_role";

grant update on table "public"."water_requests" to "service_role";

create policy "Allow anonymous token registration"
on "public"."anonymous_tokens"
as permissive
for insert
to public
with check (true);


create policy "Allow anonymous token updates"
on "public"."anonymous_tokens"
as permissive
for update
to public
using (true)
with check (true);


create policy "Allow deletion of anonymous token"
on "public"."anonymous_tokens"
as permissive
for delete
to public
using (true);


create policy "Public access to insert to cart_requests"
on "public"."cart_requests"
as permissive
for insert
to public
with check (true);


create policy "Public access to read cart_requests"
on "public"."cart_requests"
as permissive
for select
to public
using (true);


create policy "Public access to update cart_requests"
on "public"."cart_requests"
as permissive
for update
to public
using (true);


create policy "Public read access on datetime"
on "public"."datetime"
as permissive
for select
to public
using (true);


create policy "Update datetime for games"
on "public"."datetime"
as permissive
for update
to public
using (true);


create policy "Public access to deletion tokens"
on "public"."deletion_tokens"
as permissive
for all
to public
using (true);


create policy "Public read access to divisions"
on "public"."divisions"
as permissive
for select
to public
using (true);


create policy "Public read access to faqs"
on "public"."faq"
as permissive
for select
to public
using (true);


create policy "Users can delete their own favorites"
on "public"."favorite_teams"
as permissive
for delete
to public
using ((auth.uid() = user_id));


create policy "Users can insert their own favorites"
on "public"."favorite_teams"
as permissive
for insert
to public
with check ((auth.uid() = user_id));


create policy "Users can view their own favorites"
on "public"."favorite_teams"
as permissive
for select
to public
using ((auth.uid() = user_id));


create policy "Public access to insert to feedback"
on "public"."feedback"
as permissive
for insert
to public
with check (true);


create policy "Users can read feedback"
on "public"."feedback"
as permissive
for select
to public
using (true);


create policy "Public access to update fields"
on "public"."fields"
as permissive
for update
to public
using (true);


create policy "Public read access on fields"
on "public"."fields"
as permissive
for select
to public
using (true);


create policy "Public access to insert into games"
on "public"."games"
as permissive
for insert
to public
with check (true);


create policy "Public access to update games"
on "public"."games"
as permissive
for update
to public
using (true);


create policy "Public read access on games"
on "public"."games"
as permissive
for select
to public
using (true);


create policy "Public read access to schedule options"
on "public"."gametypes"
as permissive
for select
to public
using (true);


create policy "Enable delete for users on medical_requests"
on "public"."medical_requests"
as permissive
for delete
to public
using (true);


create policy "Public access to insert to medical_requests"
on "public"."medical_requests"
as permissive
for insert
to public
with check (true);


create policy "Public access to read medical_requests"
on "public"."medical_requests"
as permissive
for select
to public
using (true);


create policy "Public access to update medical_requests"
on "public"."medical_requests"
as permissive
for update
to public
using (true);


create policy "Users can mark notifications as read"
on "public"."notification_read_status"
as permissive
for insert
to public
with check ((auth.uid() = user_id));


create policy "Users can read their own read statuses"
on "public"."notification_read_status"
as permissive
for select
to public
using ((auth.uid() = user_id));


create policy "Admins can create public announcements"
on "public"."notifications"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE (profiles.is_admin = true))));


create policy "Enable read access for all users"
on "public"."notifications"
as permissive
for select
to public
using (true);


create policy "Users can update their own notifications"
on "public"."notifications"
as permissive
for update
to public
using ((auth.uid() = user_id));


create policy "Public read access on pools"
on "public"."pools"
as permissive
for select
to public
using (true);


create policy "Public profiles are viewable by everyone."
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "Users can delete their own profile."
on "public"."profiles"
as permissive
for delete
to authenticated
using ((auth.uid() = id));


create policy "Users can insert their own profile."
on "public"."profiles"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = id));


create policy "Users can update own profile."
on "public"."profiles"
as permissive
for update
to public
using (true);


create policy "Public access to update rankings"
on "public"."rankings"
as permissive
for update
to public
using (true);


create policy "Public read access on rankings"
on "public"."rankings"
as permissive
for select
to public
using (true);


create policy "Public access to restaurants"
on "public"."restaurants"
as permissive
for select
to public
using (true);


create policy "Public read access on rounds"
on "public"."rounds"
as permissive
for select
to public
using (true);


create policy "Player access to update scores"
on "public"."scores"
as permissive
for update
to public
using (true);


create policy "Public read access on scores"
on "public"."scores"
as permissive
for select
to public
using (true);


create policy "Public read access on teams"
on "public"."teams"
as permissive
for select
to public
using (true);


create policy "Public access to vendors"
on "public"."vendors"
as permissive
for select
to public
using (true);


create policy "Public read access on volunteers"
on "public"."volunteers"
as permissive
for select
to public
using (true);


create policy "Public access to delete from water_requests"
on "public"."water_requests"
as permissive
for delete
to public
using (true);


create policy "Public access to insert into water_requests"
on "public"."water_requests"
as permissive
for insert
to public
with check (true);


create policy "Public access to update water_requests"
on "public"."water_requests"
as permissive
for update
to public
using (true);


create policy "Public read access on water_requests"
on "public"."water_requests"
as permissive
for select
to public
using (true);


CREATE TRIGGER trg_cart_accepted_notifications AFTER UPDATE ON public.cart_requests FOR EACH ROW WHEN (((old.status = 'pending'::request_status) AND (new.status = 'confirmed'::request_status))) EXECUTE FUNCTION supabase_functions.http_request('https://opleqymigooimduhlvym.supabase.co/functions/v1/cart-request', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbGVxeW1pZ29vaW1kdWhsdnltIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxOTQ5ODE0MCwiZXhwIjoyMDM1MDc0MTQwfQ.bCMKqxcqFgLXYJro0uq5a6W4hR7wVJIJ8FmZ8yJE7Pw"}', '{}', '1000');

CREATE TRIGGER trg_cart_notifications AFTER INSERT ON public.cart_requests FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://opleqymigooimduhlvym.supabase.co/functions/v1/cart-request', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbGVxeW1pZ29vaW1kdWhsdnltIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxOTQ5ODE0MCwiZXhwIjoyMDM1MDc0MTQwfQ.bCMKqxcqFgLXYJro0uq5a6W4hR7wVJIJ8FmZ8yJE7Pw"}', '{}', '1000');

CREATE TRIGGER insert_score_after_game_insert AFTER INSERT ON public.games FOR EACH ROW EXECUTE FUNCTION insert_new_score();

CREATE TRIGGER trg_medic_notifications AFTER INSERT OR UPDATE ON public.medical_requests FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://opleqymigooimduhlvym.supabase.co/functions/v1/trainer-request', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbGVxeW1pZ29vaW1kdWhsdnltIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxOTQ5ODE0MCwiZXhwIjoyMDM1MDc0MTQwfQ.bCMKqxcqFgLXYJro0uq5a6W4hR7wVJIJ8FmZ8yJE7Pw"}', '{}', '1000');

CREATE TRIGGER trg_profiles_default_role BEFORE INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION ensure_profile_role_default();

CREATE TRIGGER trg_profiles_sync_flags_from_role BEFORE INSERT OR UPDATE OF role_id ON public.profiles FOR EACH ROW EXECUTE FUNCTION sync_profile_flags_from_role();

CREATE TRIGGER insert_rankings_after_score_insert AFTER INSERT ON public.scores FOR EACH ROW EXECUTE FUNCTION insert_new_rankings();

CREATE TRIGGER trg_update_rankings AFTER UPDATE ON public.scores FOR EACH ROW WHEN (((new.is_finished = true) AND (old.is_finished = false))) EXECUTE FUNCTION perform_rankings_and_tiebreakers();

CREATE TRIGGER trg_water_requests AFTER INSERT OR DELETE ON public.water_requests FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://opleqymigooimduhlvym.supabase.co/functions/v1/water-request', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbGVxeW1pZ29vaW1kdWhsdnltIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxOTQ5ODE0MCwiZXhwIjoyMDM1MDc0MTQwfQ.bCMKqxcqFgLXYJro0uq5a6W4hR7wVJIJ8FmZ8yJE7Pw"}', '{}', '1000');


