-- Multi-role access model with permissions
-- Supports users having multiple roles (e.g., driver + volunteer)

create table if not exists public.permissions (
  id smallint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id smallint not null references public.roles(id) on delete cascade,
  permission_id smallint not null references public.permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.profile_roles (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role_id smallint not null references public.roles(id) on delete cascade,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (profile_id, role_id)
);

create unique index if not exists profile_roles_one_primary_idx
  on public.profile_roles(profile_id)
  where is_primary;

insert into public.permissions (key, name, description)
values
  ('view_admin_dashboard', 'View Admin Dashboard', 'Can access admin section UI.'),
  ('manage_games', 'Manage Games', 'Can update scores and game metadata.'),
  ('manage_transport', 'Manage Transport', 'Can manage cart/transport requests.'),
  ('manage_water', 'Manage Water', 'Can manage water requests.'),
  ('manage_trainer_requests', 'Manage Trainer Requests', 'Can manage trainer requests.'),
  ('receive_cart_notifications', 'Receive Cart Notifications', 'Can receive cart request notifications.'),
  ('receive_water_notifications', 'Receive Water Notifications', 'Can receive water request notifications.'),
  ('receive_medic_notifications', 'Receive Medic Notifications', 'Can receive trainer/medic request notifications.')
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description,
  updated_at = now();

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on (
  (r.key = 'admin')
  or (r.key = 'driver' and p.key in ('manage_transport', 'receive_cart_notifications'))
  or (r.key = 'volunteer' and p.key in ('manage_water', 'receive_water_notifications'))
  or (r.key = 'medic' and p.key in ('manage_trainer_requests', 'receive_medic_notifications'))
)
on conflict (role_id, permission_id) do nothing;

-- Backfill primary role from existing profiles.role_id
insert into public.profile_roles (profile_id, role_id, is_primary)
select p.id, p.role_id, true
from public.profiles p
where p.role_id is not null
on conflict (profile_id, role_id)
do update set is_primary = excluded.is_primary;

-- Backfill additional roles from legacy flags
insert into public.profile_roles (profile_id, role_id, is_primary)
select p.id, r.id, false
from public.profiles p
join public.roles r on r.key = 'admin'
where coalesce(p.is_admin, false)
on conflict (profile_id, role_id) do nothing;

insert into public.profile_roles (profile_id, role_id, is_primary)
select p.id, r.id, false
from public.profiles p
join public.roles r on r.key = 'medic'
where coalesce(p.is_medical_staff, false)
on conflict (profile_id, role_id) do nothing;

insert into public.profile_roles (profile_id, role_id, is_primary)
select p.id, r.id, false
from public.profiles p
join public.roles r on r.key = 'driver'
where coalesce(p.is_driver, false)
on conflict (profile_id, role_id) do nothing;

insert into public.profile_roles (profile_id, role_id, is_primary)
select p.id, r.id, false
from public.profiles p
join public.roles r on r.key = 'volunteer'
where coalesce(p.is_volunteer, false)
on conflict (profile_id, role_id) do nothing;

-- Ensure each profile has exactly one primary role assignment
with missing_primary as (
  select pr.profile_id, min(pr.role_id) as role_id
  from public.profile_roles pr
  group by pr.profile_id
  having bool_or(pr.is_primary) = false
)
update public.profile_roles pr
set is_primary = true
from missing_primary mp
where pr.profile_id = mp.profile_id
  and pr.role_id = mp.role_id;

create or replace function public.sync_profile_roles_primary_from_profile()
returns trigger
language plpgsql
as $$
begin
  if new.role_id is null then
    return new;
  end if;

  update public.profile_roles
  set is_primary = false
  where profile_id = new.id;

  insert into public.profile_roles (profile_id, role_id, is_primary)
  values (new.id, new.role_id, true)
  on conflict (profile_id, role_id)
  do update set is_primary = true;

  return new;
end;
$$;

-- Keep profile_roles primary assignment in sync with profiles.role_id
drop trigger if exists trg_profiles_sync_primary_profile_role on public.profiles;

create trigger trg_profiles_sync_primary_profile_role
after insert or update of role_id on public.profiles
for each row
execute function public.sync_profile_roles_primary_from_profile();

create or replace function public.get_profile_access(p_profile_id uuid)
returns table(role_keys text[], permission_keys text[])
language sql
stable
as $$
  with assigned_roles as (
    select distinct r.key
    from public.profile_roles pr
    join public.roles r on r.id = pr.role_id
    where pr.profile_id = p_profile_id
  ),
  assigned_permissions as (
    select distinct p.key
    from public.profile_roles pr
    join public.role_permissions rp on rp.role_id = pr.role_id
    join public.permissions p on p.id = rp.permission_id
    where pr.profile_id = p_profile_id
  )
  select
    coalesce((select array_agg(ar.key order by ar.key) from assigned_roles ar), '{}'::text[]) as role_keys,
    coalesce((select array_agg(ap.key order by ap.key) from assigned_permissions ap), '{}'::text[]) as permission_keys;
$$;

grant execute on function public.get_profile_access(uuid) to anon, authenticated;

alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.profile_roles enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'permissions' and policyname = 'Public can read permissions'
  ) then
    create policy "Public can read permissions"
      on public.permissions
      for select
      to public
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'role_permissions' and policyname = 'Public can read role permissions'
  ) then
    create policy "Public can read role permissions"
      on public.role_permissions
      for select
      to public
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'profile_roles' and policyname = 'Public can read profile roles'
  ) then
    create policy "Public can read profile roles"
      on public.profile_roles
      for select
      to public
      using (true);
  end if;
end
$$;
