-- Roles-based access control foundation
-- Creates a normalized roles model and links profiles to roles.
-- Keeps existing profile boolean flags in sync for backward compatibility.

create table if not exists public.roles (
  id smallint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint roles_key_check check (key in ('user', 'admin', 'medic', 'driver', 'volunteer'))
);

-- Ensure only one default role.
create unique index if not exists roles_single_default_idx
  on public.roles (is_default)
  where is_default;

insert into public.roles (key, name, description, is_default)
values
  ('user', 'User', 'Default tournament participant role.', true),
  ('admin', 'Admin', 'Full administrative access.', false),
  ('medic', 'Medic', 'Medical support staff.', false),
  ('driver', 'Driver', 'Cart/transport support staff.', false),
  ('volunteer', 'Volunteer', 'General volunteer support.', false)
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description,
  is_default = excluded.is_default,
  updated_at = now();

do $$
begin
  if to_regclass('public.profiles') is not null then
    alter table public.profiles
      add column if not exists role_id smallint;

    alter table public.profiles
      drop constraint if exists profiles_role_id_fkey;

    alter table public.profiles
      add constraint profiles_role_id_fkey
      foreign key (role_id)
      references public.roles(id)
      on update cascade
      on delete restrict;

    create index if not exists profiles_role_id_idx
      on public.profiles(role_id);
  end if;
end
$$;

create or replace function public.get_default_role_id()
returns smallint
language sql
stable
as $$
  select r.id
  from public.roles r
  where r.is_default = true
  limit 1;
$$;

create or replace function public.sync_profile_flags_from_role()
returns trigger
language plpgsql
as $$
declare
  role_key text;
begin
  select r.key into role_key
  from public.roles r
  where r.id = new.role_id;

  if role_key is null then
    return new;
  end if;

  new.is_admin := (role_key = 'admin');
  new.is_medical_staff := (role_key = 'medic');
  new.is_driver := (role_key = 'driver');
  new.is_volunteer := (role_key = 'volunteer');

  return new;
end;
$$;

create or replace function public.ensure_profile_role_default()
returns trigger
language plpgsql
as $$
begin
  if new.role_id is null then
    new.role_id := public.get_default_role_id();
  end if;

  return new;
end;
$$;

do $$
begin
  if to_regclass('public.profiles') is not null then
    drop trigger if exists trg_profiles_default_role on public.profiles;
    create trigger trg_profiles_default_role
    before insert on public.profiles
    for each row
    execute function public.ensure_profile_role_default();

    drop trigger if exists trg_profiles_sync_flags_from_role on public.profiles;
    create trigger trg_profiles_sync_flags_from_role
    before insert or update of role_id on public.profiles
    for each row
    execute function public.sync_profile_flags_from_role();
  end if;
end
$$;

-- Backfill role_id for existing users from legacy flags.
do $$
begin
  if to_regclass('public.profiles') is not null then
    update public.profiles p
    set role_id = (
      select r.id
      from public.roles r
      where r.key = case
        when coalesce(p.is_admin, false) then 'admin'
        when coalesce(p.is_medical_staff, false) then 'medic'
        when coalesce(p.is_driver, false) then 'driver'
        when coalesce(p.is_volunteer, false) then 'volunteer'
        else 'user'
      end
    )
    where p.role_id is null;

    update public.profiles p
    set role_id = public.get_default_role_id()
    where p.role_id is null;

    alter table public.profiles
      alter column role_id set not null;
  end if;
end
$$;

-- Keep role metadata readable by signed-in users.
alter table public.roles enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'roles'
      and policyname = 'Authenticated users can read roles'
  ) then
    create policy "Authenticated users can read roles"
      on public.roles
      for select
      to authenticated
      using (true);
  end if;
end
$$;
